# Generated by Django 3.1 on 2020-08-15 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oturum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cevap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cevap', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sinav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('olusturulmatarihi', models.DateTimeField(auto_now_add=True)),
                ('sorusayisi', models.IntegerField()),
                ('C1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C1', to='oturum.cevap')),
                ('C10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C10', to='oturum.cevap')),
                ('C11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C11', to='oturum.cevap')),
                ('C12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C12', to='oturum.cevap')),
                ('C13', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C13', to='oturum.cevap')),
                ('C14', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C14', to='oturum.cevap')),
                ('C15', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C15', to='oturum.cevap')),
                ('C16', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C16', to='oturum.cevap')),
                ('C17', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C17', to='oturum.cevap')),
                ('C18', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C18', to='oturum.cevap')),
                ('C19', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C19', to='oturum.cevap')),
                ('C2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C2', to='oturum.cevap')),
                ('C20', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C20', to='oturum.cevap')),
                ('C21', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C21', to='oturum.cevap')),
                ('C22', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C22', to='oturum.cevap')),
                ('C23', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C23', to='oturum.cevap')),
                ('C24', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C24', to='oturum.cevap')),
                ('C25', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C25', to='oturum.cevap')),
                ('C26', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C26', to='oturum.cevap')),
                ('C27', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C27', to='oturum.cevap')),
                ('C28', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C28', to='oturum.cevap')),
                ('C29', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C29', to='oturum.cevap')),
                ('C3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C3', to='oturum.cevap')),
                ('C30', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C30', to='oturum.cevap')),
                ('C31', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C31', to='oturum.cevap')),
                ('C32', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C32', to='oturum.cevap')),
                ('C33', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C33', to='oturum.cevap')),
                ('C34', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C34', to='oturum.cevap')),
                ('C35', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C35', to='oturum.cevap')),
                ('C36', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C36', to='oturum.cevap')),
                ('C37', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C37', to='oturum.cevap')),
                ('C38', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C38', to='oturum.cevap')),
                ('C39', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C39', to='oturum.cevap')),
                ('C4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C4', to='oturum.cevap')),
                ('C40', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C40', to='oturum.cevap')),
                ('C41', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C41', to='oturum.cevap')),
                ('C42', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C42', to='oturum.cevap')),
                ('C43', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C43', to='oturum.cevap')),
                ('C44', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C44', to='oturum.cevap')),
                ('C45', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C45', to='oturum.cevap')),
                ('C46', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C46', to='oturum.cevap')),
                ('C47', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C47', to='oturum.cevap')),
                ('C48', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C48', to='oturum.cevap')),
                ('C49', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C49', to='oturum.cevap')),
                ('C5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C5', to='oturum.cevap')),
                ('C50', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C50', to='oturum.cevap')),
                ('C6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C6', to='oturum.cevap')),
                ('C7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C7', to='oturum.cevap')),
                ('C8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C8', to='oturum.cevap')),
                ('C9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C9', to='oturum.cevap')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oturum.ders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
