# Generated by Django 3.1 on 2020-08-15 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oturum', '0002_cevap_sinav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinav',
            name='C1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C1', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C10',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C10', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C11',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C11', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C12',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C12', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C13',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C13', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C14',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C14', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C15',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C15', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C16',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C16', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C17',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C17', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C18',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C18', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C19',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C19', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C2', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C20',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C20', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C21',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C21', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C22',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C22', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C23',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C23', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C24',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C24', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C25',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C25', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C26',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C26', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C27',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C27', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C28',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C28', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C29',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C29', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C3', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C30',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C30', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C31',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C31', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C32',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C32', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C33',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C33', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C34',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C34', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C35',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C35', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C36',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C36', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C37',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C37', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C38',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C38', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C39',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C39', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C4',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C4', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C40',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C40', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C41',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C41', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C42',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C42', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C43',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C43', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C44',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C44', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C45',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C45', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C46',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C46', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C47',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C47', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C48',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C48', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C49',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C49', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C5',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C5', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C50',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C50', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C6',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C6', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C7',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C7', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C8',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C8', to='oturum.cevap'),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='C9',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C9', to='oturum.cevap'),
        ),
    ]
