# Generated by Django 3.1 on 2020-08-22 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oturum', '0006_ogrencicevap_ogrencipuan_sorukazanim_sorupuanlama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorupuanlama',
            name='sinav',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oturum.sinav'),
        ),
    ]
