# Generated by Django 3.1 on 2020-08-23 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oturum', '0008_auto_20200822_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorukazanim',
            name='ders',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='oturum.ders'),
            preserve_default=False,
        ),
    ]
