# Generated by Django 3.1 on 2020-08-23 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oturum', '0009_sorukazanim_ders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorukazanim',
            name='ders',
        ),
    ]
